### ISSUE TITLE
Unable to build Next JS project with @preact-signals/safe-react

### ISSUE THREAD

**Issue by antoinedelplace** [XantreGodlike/preact-signals#82]
Hello there! :)

I am trying to use signals in my project without success.
I have just installed the library in my project and tried to build.

Here is the error I am getting:
```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: (0 , E.useRef) is not a function
    at N (...project\.next\server\chunks\68.js:22:20581)
    at o (...project\.next\server\app\page.js:1:2917)
    at em (...project\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:131226)
    at ...project\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:142926
    at Array.toJSON (...project\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:146504)
    at stringify (<anonymous>)
    at eR (...project\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:134889)
    at eP (...project\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:135332)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Timeout._onTimeout (...project\node_modules\.pnpm\next@14.1.0_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:146956)
 ```
    
 I have the same error for all my pages.
 Here are my package :
 ```
 "dependencies": {
    "@dnd-kit/core": "^6.1.0",
    "@dnd-kit/modifiers": "^7.0.0",
    "@dnd-kit/utilities": "^3.2.2",
    "@next-auth/prisma-adapter": "^1.0.7",
    "@preact-signals/safe-react": "^0.5.3",
    "@prisma/client": "^5.9.1",
    "@radix-ui/react-dialog": "^1.0.5",
    "@radix-ui/react-popover": "^1.0.7",
    "@radix-ui/react-tooltip": "^1.0.7",
    "@types/node": "18.11.18",
    "@types/react": "18.2.24",
    "@types/react-dom": "18.2.8",
    "@vercel/analytics": "^0.1.11",
    "@vercel/og": "^0.0.26",
    "@vercel/speed-insights": "^1.0.10",
    "classnames": "^2.3.2",
    "clsx": "^2.0.0",
    "eslint": "8.31.0",
    "eslint-config-next": "13.1.1",
    "focus-trap-react": "^10.2.2",
    "framer-motion": "^8.5.5",
    "lucide-react": "0.105.0-alpha.4",
    "ms": "^2.1.3",
    "next": "^14.1.0",
    "next-auth": "^4.22.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-icons": "^5.0.1",
    "react-markdown": "^8.0.7",
    "tailwind-merge": "^1.14.0",
    "typescript": "5.2.2",
    "use-debounce": "^9.0.4",
    "vaul": "^0.6.8"
  }
  ```
  And my config :
  ```
  /** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "lh3.googleusercontent.com",
      },
    ],
  },
  experimental: {
    swcPlugins: [
      ["@preact-signals/safe-react/swc", {}],
    ],
  },
};

module.exports = nextConfig;
  ```
  
  Am I missing something ? Can someone help please ? :)

**Comment by XantreGodlike** [comment]
Probably some of your server component have been transpiled.
Here are the ways how you can fix it https://github.com/XantreGodlike/preact-signals/blob/main/packages%2Freact%2FREADME.md#automatic-integration-with-server-components-maybe-one-of-these-should-be-marked-as-a-client-entry-with-use-client

For your case - the best way is to use 'auto' mode

**Comment by antoinedelplace** [comment]
Thank you @XantreGodlike !

It works using the option "auto" :
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "lh3.googleusercontent.com",
      },
    ],
  },
  experimental: {
    swcPlugins: [
      ["@preact-signals/safe-react/swc", {mode: "auto",}],
    ],
  },
};

module.exports = nextConfig;
```
